#page title
page_title                                : KinoCalc                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.hesnorth.kinocalc                                         # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/Artboard 1xhdpi.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : KinoCalc                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free with Ads / Pay What You Want                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Tools for Cinematography and Lighting

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                 
your_link                                 :                      
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Quick input
    description                           : Custom designed input sliders for quick and precise value adjustments on the fly.
    fontawesome_icon_name                 : sliders-h
    
  - title                                 : Choose your input
    description                           : Your inputs and outputs aren't fixed in KinoCalc. Calculate DOF, or input your desired DOF and let KinoCalc calculate the camera changes needed to achieve it. 
    fontawesome_icon_name                 : equals

  - title                                 : Responsive visualisation
    description                           : KinoCalc visualises your DOF in a way that's intuitive and sensible.
    fontawesome_icon_name                 : tv

  - title                                 : DOF Calculator 
    description                           : Calculate how to set up the perfect Depth of Field for your shot.
    fontawesome_icon_name                 : video

  - title                                 : Focal Length Matcher
    description                           : Find the lens required to match focal length between different cameras.
    fontawesome_icon_name                 : ruler
  
  - title                                 : Exposure Compensation Calculator
    description                           : Determines what changes must be made to counteract changes in exposure.
    fontawesome_icon_name                 : lightbulb
  
  - title                                 : Safe Panning Calculator
    description                           : Calculate the maximum speed for a slow-pan to prevent juttering.
    fontawesome_icon_name                 : sync-alt

  - title                                 : Solar Elevation Calculator
    description                           : Calculate the angle of the sun and the phase of the moon at any time, at any place on Earth.
    fontawesome_icon_name                 : sun

  - title                                 : Triangulation Calculator
    description                           : Calculate any side or angle on a right-triangle. Perfect for calculating circle of confusion, lamp beam spread, etc.
    fontawesome_icon_name                 : ruler-combined

  - title                                 : Eyelight / Chromakey Tool
    description                           : Eyelight with full RGB or colour temperature options, with optional VFX tracking markers.
    fontawesome_icon_name                 : eye

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
